---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json

name: kino
description: My Kinoite image
base-image: ghcr.io/ublue-os/kinoite-main
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: dnf
    repos:
      copr:
        - toroidalfox/kime
	- atim/starship
    install:
      packages:
        - kime-git
        - emacs
        - neovim
        - perl-core
        - zathura
        - zathura-pdf-poppler
        - alacritty
        - kitty
	- starship
        - eza
        - zoxide
        - btop
        - bat
        - ripgrep
        - fd-find
        - git-delta
        - trash-cli
        - fastfetch
        - fzf
        - jq
        - papirus-icon-theme
        - chezmoi
        - p7zip
        - powertop
        - podman-compose
        - tailscale
        - gh
    remove:
      packages:
        - firefox
        - firefox-langpacks

  - type: brew
    nofile-limits: true
    brew-analytics: false
    install:
      - zsh-autosuggestions
      - zsh-syntax-highlighting
      - isync
      - mu

  - type: default-flatpaks
    configurations:
      - notify: false
        scope: system
        install:
          - app.zen_browser.zen
          - eu.betterbird.Betterbird
          - me.proton.Mail
          - com.spotify.Client
          - org.libreoffice.LibreOffice
          - com.bitwarden.desktop
          - com.protonvpn.www
          - org.fkoehler.KTailctl
          - com.github.zocker_160.SyncThingy
          - org.fedoraproject.MediaWriter
          - com.github.tchx84.Flatseal
      - notify: false
        scope: user

  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode
        - Hack
        - SourceCodePro
        - JetBrainsMono
        - NerdFontsSymbolsOnly
      google-fonts:
        - Roboto
        - NotoSansKorean

  - type: systemd
    system:
      enabled:
        - tailscaled.service
    user:
      enabled:
        - emacs.service

  - type: script
    scripts:
      - dirs.sh

  - type: signing
