---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json

name: kino
description: My Kinoite image

base-image: ghcr.io/ublue-os/kinoite-main
image-version: latest

modules:
  # ── Files ─────────────────────────────────────────────────────
  - type: files
    files:
      - source: system
        destination: /
	
  # ── System Packages ───────────────────────────────────────────
  - type: dnf
    repos:
      copr:
        - toroidalfox/kime
    install:
      packages:
        # Input method
        - kime-git
	# Editors
	- emacs
	- neovim
	# LaTeX
	- perl-core
	# Document viewer
	- zathura
	- zathura-pdf-poppler
	# Terminal
	- alacritty
	- kitty
	# CLI
	- eza
	- zoxide
	- btop
	- bat
	- ripgrep
	- fd-find
	- git-delta
	- trash-cli
	- fastfetch
	- fzf
	- jq
	# Theming
	- papirus-icon-theme
	# Utilities
	- chezmoi
	- p7zip
	- powertop
	- podman-compose
	- tailscale
	- gh
    remove:
      packages:
        - firefox
        - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)
	
  # ── Brew ──────────────────────────────────────────────────────
  - type: brew
    nofile-limits: true
    brew-analytics: false

  # ── Flatpaks ──────────────────────────────────────────────────
  - type: default-flatpaks
    configurations:
      - notify: false
        scope: system
        install:
          # Browser
          - app.zen_browser.zen

          # Terminal
          - com.mitchellh.ghostty

          # Communication
          - eu.betterbird.Betterbird
          - me.proton.Mail

          # Media & productivity
          - com.spotify.Client
          - org.libreoffice.LibreOffice

          # Security & networking
          - com.bitwarden.desktop
          - com.protonvpn.www
          - org.fkoehler.KTailctl

          # Sync & system tools
          - com.github.zocker_160.SyncThingy
          - org.fedoraproject.MediaWriter
          - com.github.tchx84.Flatseal
      - notify: false
        scope: user

  # ── Fonts ─────────────────────────────────────────────────────
  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode
        - Hack
        - SourceCodePro
        - JetBrainsMono
        - NerdFontsSymbolsOnly
      google-fonts:
        - Roboto
        - NotoSansKorean

  # ── Systemd Services ──────────────────────────────────────────
  - type: systemd
    system:
      enabled:
        - tailscaled.service
    user:
      enabled:
        - emacs.service

  # ── Scripts ───────────────────────────────────────────────────
  - type: script
    scripts:
      - dirs.sh

  # ── Signing ───────────────────────────────────────────────────
  - type: signing
